#!/usr/bin/env bash
# Configure server with: Nginx
# Add to HTTP header


ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

# configure server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Header is updated (add_header to file)
sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default

# start server
sudo service nginx restart