#!/usr/bin/env bash
# Configure server with: Nginx
# Add to HTTP header


# Get the hostname of the server
HOSTNAME=$(hostname)

# Create the custom header using the server's hostname
ADD_HEADER="add_header X-Served-By $HOSTNAME;"

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Create a simple Hello World index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Remove 'default_server' from the default Nginx configuration
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Add the custom header to the Nginx configuration
sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
