#!/usr/bin/env bash
#Requirement: Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL

# Reload Nginx to apply the new configuration
systemctl reload nginx
