#!usr/bin/bash
#install ufw and allow port 22, 80 and 44

sudo apt update
sudo apt-get install ufw
sudo ufw status
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw reload
