#!usr/bin/bash
#install ufw and allow port 22, 80 and 44

sudo apt update
sudo apt-get install ufw
sudo ufw status
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 3.84.239.242:80
sudo iptables -t nat -A POSTROUTING -j MASQUERADE
sudo ufw reload
