#!/usr/bin/env bash
#Fix curl error message by starting Apache service

echo "Hello World!" | sudo tee /usr/local/apache2/htdocs/index.html
docker build -t my-apache-image .
docker run -d -p 80:80 --name my-apache-container my-apache-image